(function() {var implementors = {};
implementors["libc"] = [];implementors["enum_primitive"] = [];implementors["serde"] = ["impl&lt;'a,&nbsp;B&gt; <a class='trait' href='core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='enum' href='https://doc.rust-lang.org/nightly/collections/borrow/enum.Cow.html' title='collections::borrow::Cow'>Cow</a>&lt;'a,&nbsp;B&gt; <span class='where'>where B: <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='collections::borrow::ToOwned'>ToOwned</a> + ?<a class='trait' href='core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a></span>","impl <a class='trait' href='core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/collections/string/struct.String.html' title='collections::string::String'>String</a>","impl&lt;T&gt; <a class='trait' href='core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html' title='collections::vec::Vec'>Vec</a>&lt;T&gt;","impl&lt;T&gt; <a class='trait' href='core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a></span>","impl <a class='trait' href='core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='serde/bytes/struct.ByteBuf.html' title='serde::bytes::ByteBuf'>ByteBuf</a>","impl&lt;'a&gt; <a class='trait' href='core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='serde/bytes/struct.Bytes.html' title='serde::bytes::Bytes'>Bytes</a>&lt;'a&gt;",];implementors["image"] = ["impl&lt;P,&nbsp;Container&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='image/struct.ImageBuffer.html' title='image::ImageBuffer'>ImageBuffer</a>&lt;P,&nbsp;Container&gt; <span class='where'>where P: <a class='trait' href='image/trait.Pixel.html' title='image::Pixel'>Pixel</a> + 'static, P::Subpixel: 'static, Container: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a>&lt;Target=<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>[</a>P::Subpixel<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>]</a>&gt;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
